-- Durable Sheets handoff authority.  No legacy rows are backfilled by this migration.
CREATE TABLE sheet_handoffs (
 id INTEGER PRIMARY KEY,
 generation_id INTEGER NOT NULL REFERENCES generations(id) ON DELETE RESTRICT,
 approval_event_id INTEGER NOT NULL UNIQUE REFERENCES decision_events(id) ON DELETE RESTRICT,
 target_binding_id INTEGER NOT NULL,
 export_id TEXT NOT NULL CHECK(length(export_id)=36 AND substr(export_id,1,4)='exp_' AND length(substr(export_id,5))=32 AND substr(export_id,5) NOT GLOB '*[^0-9a-f]*'),
 canonical_bytes BLOB NOT NULL CHECK(length(canonical_bytes)>0),
 canonical_sha256 TEXT NOT NULL CHECK(length(canonical_sha256)=64 AND canonical_sha256 NOT GLOB '*[^0-9a-f]*' AND canonical_sha256=sha256_hex(canonical_bytes)),
 approved_at TEXT NOT NULL, category TEXT NOT NULL CHECK(category IN ('AI','Blockchain')),
 initial_upload_status TEXT NOT NULL CHECK(initial_upload_status='X'),
 marker_value TEXT NOT NULL CHECK(marker_value='v1:' || export_id || ':' || canonical_sha256), status TEXT NOT NULL CHECK(status IN ('pending','retryable','delivering','ambiguous','delivered','blocked','corrupt','manual_required')),
 safe_error_code TEXT CHECK(safe_error_code IS NULL OR safe_error_code IN ('template_drift','metadata_conflict','not_found','invalid_request','unauthenticated','permission_denied','rate_limited','aborted','ambiguous','rejected_retryable','rejected_blocked','abandoned_pre_marker','duplicate_metadata','conflicting_metadata','schema_conflict','local_corrupt','operator_unresolved')), retry_at TEXT, delivered_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(generation_id,approval_event_id), UNIQUE(id,status), CHECK((status='retryable')=(retry_at IS NOT NULL)), CHECK(retry_at IS NULL OR aware_epoch_us(retry_at) IS NOT NULL), CHECK((status='delivered')=(delivered_at IS NOT NULL)), CHECK(status!='delivered' OR safe_error_code IS NULL), FOREIGN KEY(id,target_binding_id) REFERENCES sheet_handoff_bindings(handoff_id,target_binding_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE sheet_target_bindings (
 id INTEGER PRIMARY KEY, target_ref_sha256 TEXT NOT NULL UNIQUE CHECK(length(target_ref_sha256)=64 AND target_ref_sha256 NOT GLOB '*[^0-9a-f]*'),
 schema_version TEXT NOT NULL CHECK(schema_version='workplace-template-v1'), sheet_id INTEGER NOT NULL CHECK(sheet_id=0), sheet_title TEXT NOT NULL CHECK(sheet_title='workplace'),
 oracle_fingerprint TEXT NOT NULL CHECK(length(oracle_fingerprint)=64 AND oracle_fingerprint NOT GLOB '*[^0-9a-f]*'), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(schema_version,sheet_id,sheet_title)
);
CREATE TABLE sheet_handoff_bindings (
 handoff_id INTEGER PRIMARY KEY REFERENCES sheet_handoffs(id) ON DELETE RESTRICT, target_binding_id INTEGER NOT NULL REFERENCES sheet_target_bindings(id) ON DELETE RESTRICT, bound_at TEXT NOT NULL, UNIQUE(handoff_id,target_binding_id)
);
CREATE TABLE sheet_bootstraps (
 target_binding_id INTEGER PRIMARY KEY REFERENCES sheet_target_bindings(id) ON DELETE RESTRICT, marker_value TEXT NOT NULL, controls_fingerprint TEXT NOT NULL CHECK(length(controls_fingerprint)=64 AND controls_fingerprint NOT GLOB '*[^0-9a-f]*'),
 status TEXT NOT NULL CHECK(status IN ('uninitialized','retryable','configuring','ambiguous','ready','blocked','manual_required')), safe_error_code TEXT CHECK(safe_error_code IS NULL OR safe_error_code IN ('template_drift','metadata_conflict','not_found','invalid_request','unauthenticated','permission_denied','rate_limited','aborted','ambiguous','rejected_retryable','rejected_blocked','abandoned_pre_marker','duplicate_metadata','conflicting_metadata','schema_conflict','local_corrupt','operator_unresolved')), retry_at TEXT, verified_at TEXT,
 UNIQUE(target_binding_id,status), CHECK((status='retryable')=(retry_at IS NOT NULL)), CHECK(retry_at IS NULL OR aware_epoch_us(retry_at) IS NOT NULL), CHECK(status!='ready' OR verified_at IS NOT NULL)
);
CREATE TABLE sheet_remote_operations (
 id INTEGER PRIMARY KEY, target_binding_id INTEGER NOT NULL REFERENCES sheet_target_bindings(id) ON DELETE RESTRICT,
 operation_kind TEXT NOT NULL CHECK(operation_kind IN ('bootstrap','delivery')), handoff_id INTEGER REFERENCES sheet_handoffs(id) ON DELETE RESTRICT,
 ordinal INTEGER NOT NULL CHECK(ordinal>0), status TEXT NOT NULL CHECK(status IN ('acquired','possibly_sent','applied','rejected_retryable','rejected_blocked','abandoned_pre_marker','blocked','corrupt','manual_required')),
 certainty TEXT NOT NULL CHECK(certainty IN ('not_dispatched','possibly_sent','settled_not_applied','settled_applied','operator_unresolved')),
 last_fence_version INTEGER NOT NULL DEFAULT 1 CHECK(last_fence_version>0), current_acquired_event_id INTEGER NOT NULL, current_lease_id INTEGER NOT NULL, acquired_at TEXT NOT NULL, dispatch_at TEXT, diagnostic_probe_at TEXT,
 request_sha256 TEXT CHECK(request_sha256 IS NULL OR (length(request_sha256)=64 AND request_sha256 NOT GLOB '*[^0-9a-f]*')),
 preflight_event_id INTEGER, preflight_fence_version INTEGER, preflight_at TEXT,
 validated_oracle_fingerprint TEXT CHECK(validated_oracle_fingerprint IS NULL OR (length(validated_oracle_fingerprint)=64 AND validated_oracle_fingerprint NOT GLOB '*[^0-9a-f]*')),
 validated_controls_fingerprint TEXT CHECK(validated_controls_fingerprint IS NULL OR (length(validated_controls_fingerprint)=64 AND validated_controls_fingerprint NOT GLOB '*[^0-9a-f]*')),
 credential_refreshed_at TEXT, credential_expires_at TEXT, credential_scope_ok INTEGER CHECK(credential_scope_ok IS NULL OR credential_scope_ok=1),
 finished_at TEXT, outcome TEXT CHECK(outcome IN ('applied','reused','rejected_retryable','rejected_blocked','abandoned_pre_marker','duplicate_metadata','conflicting_metadata','schema_conflict','local_corrupt','operator_unresolved')),
 safe_error_code TEXT CHECK(safe_error_code IS NULL OR safe_error_code IN ('template_drift','metadata_conflict','not_found','invalid_request','unauthenticated','permission_denied','rate_limited','aborted','ambiguous','rejected_retryable','rejected_blocked','abandoned_pre_marker','duplicate_metadata','conflicting_metadata','schema_conflict','local_corrupt','operator_unresolved')),
 settlement_id INTEGER, UNIQUE(target_binding_id,ordinal),
 CHECK((operation_kind='bootstrap' AND handoff_id IS NULL) OR (operation_kind='delivery' AND handoff_id IS NOT NULL)),
 CHECK((dispatch_at IS NULL AND diagnostic_probe_at IS NULL AND request_sha256 IS NULL) OR (dispatch_at IS NOT NULL AND diagnostic_probe_at IS NOT NULL AND request_sha256 IS NOT NULL)),
 CHECK((preflight_event_id IS NULL AND preflight_fence_version IS NULL AND preflight_at IS NULL AND validated_oracle_fingerprint IS NULL AND validated_controls_fingerprint IS NULL AND credential_refreshed_at IS NULL AND credential_expires_at IS NULL AND credential_scope_ok IS NULL) OR (preflight_event_id IS NOT NULL AND preflight_fence_version IS NOT NULL AND preflight_fence_version>0 AND aware_epoch_us(preflight_at) IS NOT NULL AND validated_oracle_fingerprint IS NOT NULL AND validated_controls_fingerprint IS NOT NULL AND aware_epoch_us(credential_refreshed_at) IS NOT NULL AND aware_epoch_us(credential_expires_at) IS NOT NULL AND credential_scope_ok=1)),
 CHECK((finished_at IS NULL)=(outcome IS NULL)),
 CHECK(status!='acquired' OR (certainty='not_dispatched' AND dispatch_at IS NULL AND finished_at IS NULL)),
 CHECK(status!='possibly_sent' OR (certainty='possibly_sent' AND dispatch_at IS NOT NULL AND finished_at IS NULL)),
 CHECK(status!='applied' OR (certainty='settled_applied' AND finished_at IS NOT NULL)),
 CHECK(status NOT IN ('rejected_retryable','rejected_blocked') OR (certainty='settled_not_applied' AND finished_at IS NOT NULL)),
 CHECK(status!='abandoned_pre_marker' OR (certainty='not_dispatched' AND dispatch_at IS NULL AND finished_at IS NOT NULL)),
 CHECK(status='blocked' OR status='corrupt' OR status!='manual_required' OR (certainty='operator_unresolved' AND finished_at IS NOT NULL)),
 CHECK(
  (status='acquired' AND outcome IS NULL AND safe_error_code IS NULL) OR
  (status='possibly_sent' AND outcome IS NULL AND safe_error_code IS NULL) OR
  (status='applied' AND certainty='settled_applied' AND outcome IN ('applied','reused') AND safe_error_code IS NULL) OR
  (status='rejected_retryable' AND certainty='settled_not_applied' AND outcome='rejected_retryable') OR
  (status='rejected_blocked' AND certainty='settled_not_applied' AND outcome='rejected_blocked') OR
  (status='abandoned_pre_marker' AND certainty='not_dispatched' AND outcome='abandoned_pre_marker' AND safe_error_code='abandoned_pre_marker') OR
  (status='blocked' AND ((certainty='settled_applied' AND outcome IN ('duplicate_metadata','conflicting_metadata')) OR (certainty='settled_not_applied' AND outcome='schema_conflict')) AND safe_error_code=outcome) OR
  (status='corrupt' AND certainty='settled_not_applied' AND outcome='local_corrupt' AND safe_error_code='local_corrupt') OR
  (status='manual_required' AND certainty='operator_unresolved' AND outcome='operator_unresolved' AND safe_error_code='operator_unresolved')
 ),
 CHECK((finished_at IS NULL AND settlement_id IS NULL) OR (finished_at IS NOT NULL AND settlement_id IS NOT NULL)),
 CHECK(aware_epoch_us(acquired_at) IS NOT NULL AND (dispatch_at IS NULL OR aware_epoch_us(dispatch_at) IS NOT NULL) AND (finished_at IS NULL OR aware_epoch_us(finished_at) IS NOT NULL)),
 FOREIGN KEY(settlement_id,id,last_fence_version,status,outcome) REFERENCES sheet_operation_settlements(id,operation_id,fence_version,operation_status,outcome) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(current_acquired_event_id,id,last_fence_version) REFERENCES sheet_operation_events(id,operation_id,fence_version) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(current_lease_id,id,last_fence_version) REFERENCES sheet_operation_leases(id,operation_id,fence_version) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(preflight_event_id,id,preflight_fence_version) REFERENCES sheet_operation_events(id,operation_id,fence_version) DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX one_open_remote_operation_per_binding ON sheet_remote_operations(target_binding_id) WHERE finished_at IS NULL;
CREATE UNIQUE INDEX one_open_delivery_per_handoff ON sheet_remote_operations(handoff_id) WHERE handoff_id IS NOT NULL AND finished_at IS NULL;
CREATE TABLE sheet_operation_leases (
 id INTEGER PRIMARY KEY, operation_id INTEGER NOT NULL REFERENCES sheet_remote_operations(id) ON DELETE RESTRICT, fence_version INTEGER NOT NULL CHECK(fence_version>0),
 owner_token_hash TEXT NOT NULL UNIQUE CHECK(length(owner_token_hash)=64 AND owner_token_hash NOT GLOB '*[^0-9a-f]*'), lease_mode TEXT NOT NULL CHECK(lease_mode IN ('mutate','probe')),
 acquired_at TEXT NOT NULL, expires_at TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','released','expired')), finished_at TEXT, finish_reason TEXT CHECK(finish_reason IN ('preflight_exact','preflight_absent','dispatch_marked','trusted_rejection','transport_ambiguous','probe_exact','probe_absent','probe_duplicate','probe_conflict','probe_unavailable','lease_expired_pre_marker','operator_manual_required','finalized')),
 UNIQUE(operation_id,fence_version), UNIQUE(id,operation_id,fence_version), CHECK(aware_epoch_us(acquired_at) IS NOT NULL AND aware_epoch_us(expires_at)>aware_epoch_us(acquired_at)), CHECK((status='active' AND finished_at IS NULL AND finish_reason IS NULL) OR (status IN ('released','expired') AND finished_at IS NOT NULL AND aware_epoch_us(finished_at) IS NOT NULL AND finish_reason IS NOT NULL))
);
CREATE UNIQUE INDEX one_active_sheet_operation_lease ON sheet_operation_leases(operation_id) WHERE status='active';
CREATE TABLE sheet_operation_events (
 id INTEGER PRIMARY KEY, operation_id INTEGER NOT NULL REFERENCES sheet_remote_operations(id) ON DELETE RESTRICT, fence_version INTEGER NOT NULL CHECK(fence_version>0),
 event_kind TEXT NOT NULL CHECK(event_kind IN ('acquired','preflight_exact','preflight_absent','preflight_conflict','dispatch_marked','trusted_rejection','transport_ambiguous','probe_exact','probe_absent','probe_duplicate','probe_conflict','probe_unavailable','lease_expired_pre_marker','operator_manual_required','operator_corrected','finalized')),
 safe_code TEXT CHECK(safe_code IS NULL OR safe_code IN ('template_drift','metadata_conflict','not_found','invalid_request','unauthenticated','permission_denied','rate_limited','aborted','ambiguous','applied','reused','rejected_retryable','rejected_blocked','abandoned_pre_marker','duplicate_metadata','conflicting_metadata','schema_conflict','local_corrupt','operator_unresolved')), occurred_at TEXT NOT NULL CHECK(aware_epoch_us(occurred_at) IS NOT NULL), UNIQUE(operation_id,fence_version,event_kind,occurred_at), UNIQUE(id,operation_id,fence_version)
);
CREATE TABLE sheet_operation_probes (
 id INTEGER PRIMARY KEY, operation_id INTEGER NOT NULL REFERENCES sheet_remote_operations(id) ON DELETE RESTRICT, fence_version INTEGER NOT NULL CHECK(fence_version>0),
 result TEXT NOT NULL CHECK(result IN ('exact','absent','duplicate','conflict','unavailable')), matching_marker_count INTEGER NOT NULL CHECK(matching_marker_count>=0), observed_at TEXT NOT NULL,
 CHECK(aware_epoch_us(observed_at) IS NOT NULL), CHECK((result='exact' AND matching_marker_count=1) OR (result='absent' AND matching_marker_count=0) OR (result='duplicate' AND matching_marker_count>=2) OR (result='conflict' AND matching_marker_count>=1) OR (result='unavailable' AND matching_marker_count=0))
);
CREATE TABLE sheet_operation_settlements (
 id INTEGER PRIMARY KEY, operation_id INTEGER NOT NULL REFERENCES sheet_remote_operations(id) ON DELETE RESTRICT,
 fence_version INTEGER NOT NULL CHECK(fence_version>0),
 operation_status TEXT NOT NULL CHECK(operation_status IN ('applied','rejected_retryable','rejected_blocked','abandoned_pre_marker','blocked','corrupt','manual_required')),
 outcome TEXT NOT NULL CHECK(outcome IN ('applied','reused','rejected_retryable','rejected_blocked','abandoned_pre_marker','duplicate_metadata','conflicting_metadata','schema_conflict','local_corrupt','operator_unresolved')),
 subject_status TEXT NOT NULL CHECK(subject_status IN ('retryable','delivered','ready','blocked','corrupt','manual_required')),
 lease_status TEXT NOT NULL CHECK(lease_status IN ('released','expired')),
 lease_reason TEXT NOT NULL CHECK(lease_reason IN ('trusted_rejection','lease_expired_pre_marker','operator_manual_required','finalized')),
 settled_at TEXT NOT NULL CHECK(aware_epoch_us(settled_at) IS NOT NULL),
 UNIQUE(id,operation_id,fence_version,operation_status,outcome)
);

CREATE TRIGGER handoff_no_delete BEFORE DELETE ON sheet_handoffs BEGIN SELECT RAISE(ABORT,'sheet handoff cannot be deleted'); END;
CREATE TRIGGER handoff_update BEFORE UPDATE ON sheet_handoffs BEGIN
 SELECT CASE WHEN NEW.generation_id!=OLD.generation_id OR NEW.approval_event_id!=OLD.approval_event_id OR NEW.export_id!=OLD.export_id OR NEW.canonical_bytes!=OLD.canonical_bytes OR NEW.canonical_sha256!=OLD.canonical_sha256 OR NEW.approved_at!=OLD.approved_at OR NEW.category!=OLD.category OR NEW.initial_upload_status!=OLD.initial_upload_status OR NEW.marker_value!=OLD.marker_value OR NEW.created_at!=OLD.created_at THEN RAISE(ABORT,'sheet handoff identity is immutable') END;
 SELECT CASE WHEN OLD.status IN ('delivered','corrupt','manual_required') THEN RAISE(ABORT,'terminal handoff is immutable') END;
 SELECT CASE WHEN NOT ((OLD.status IN ('pending','retryable') AND NEW.status='delivering') OR (OLD.status='delivering' AND NEW.status IN ('delivered','retryable','blocked','corrupt','ambiguous')) OR (OLD.status='ambiguous' AND NEW.status IN ('delivered','retryable','blocked','corrupt','manual_required')) OR (OLD.status='blocked' AND NEW.status='retryable')) THEN RAISE(ABORT,'illegal handoff transition') END;
 SELECT CASE WHEN OLD.status='ambiguous' AND NEW.status='retryable' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version AND e.event_kind='trusted_rejection' WHERE o.handoff_id=OLD.id AND o.status='rejected_retryable' AND aware_epoch_us(NEW.retry_at)>aware_epoch_us(e.occurred_at)) THEN RAISE(ABORT,'retry deadline invalid') END;
 SELECT CASE WHEN OLD.status='blocked' AND NEW.status='retryable' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version AND e.event_kind='operator_corrected' AND e.safe_code=OLD.safe_error_code AND e.occurred_at=NEW.retry_at WHERE o.handoff_id=OLD.id AND o.finished_at IS NOT NULL AND (o.status='rejected_blocked' OR (o.status='blocked' AND o.outcome='schema_conflict' AND o.certainty='settled_not_applied')) AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations open WHERE open.target_binding_id=o.target_binding_id AND open.finished_at IS NULL)) THEN RAISE(ABORT,'operator correction invalid') END;
 SELECT CASE WHEN NOT (OLD.status='blocked' AND NEW.status='retryable') AND NOT EXISTS(
   SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.operation_id=o.id AND l.fence_version=o.last_fence_version AND l.status='active'
   JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version
   WHERE o.handoff_id=OLD.id AND (
    (OLD.status IN ('pending','retryable') AND NEW.status='delivering' AND (OLD.status='pending' OR aware_epoch_us(OLD.retry_at)<=aware_epoch_us(e.occurred_at)) AND l.lease_mode='mutate' AND o.status='acquired' AND e.event_kind='acquired')
    OR (OLD.status='delivering' AND NEW.status='ambiguous' AND l.lease_mode='mutate' AND o.status='possibly_sent' AND e.event_kind='dispatch_marked')
    OR (OLD.status='delivering' AND NEW.status='retryable' AND l.lease_mode='mutate' AND o.status='abandoned_pre_marker' AND e.event_kind='lease_expired_pre_marker')
    OR (OLD.status='delivering' AND NEW.status IN ('delivered','blocked','corrupt') AND e.event_kind='finalized')
    OR (OLD.status='ambiguous' AND NEW.status IN ('delivered','blocked','corrupt','manual_required') AND e.event_kind IN ('finalized','operator_manual_required'))
    OR (OLD.status='ambiguous' AND NEW.status='retryable' AND l.lease_mode='mutate' AND o.status='rejected_retryable' AND e.event_kind='trusted_rejection')
    OR (OLD.status='ambiguous' AND NEW.status='blocked' AND l.lease_mode='mutate' AND o.status='rejected_blocked' AND e.event_kind='trusted_rejection')
   )
 ) THEN RAISE(ABORT,'handoff transition lacks active lease event') END;
END;
CREATE TRIGGER target_no_update BEFORE UPDATE ON sheet_target_bindings BEGIN SELECT RAISE(ABORT,'sheet target binding is immutable'); END;
CREATE TRIGGER target_no_delete BEFORE DELETE ON sheet_target_bindings BEGIN SELECT RAISE(ABORT,'sheet target binding cannot be deleted'); END;
CREATE TRIGGER handoff_binding_insert BEFORE INSERT ON sheet_handoff_bindings BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM sheet_handoffs h WHERE h.id=NEW.handoff_id AND h.status='pending') OR EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.handoff_id=NEW.handoff_id) THEN RAISE(ABORT,'handoff binding requires pending unoperated handoff') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM sheet_handoff_bindings b JOIN sheet_handoffs x ON x.id=b.handoff_id JOIN sheet_handoffs h ON h.id=NEW.handoff_id WHERE x.export_id=h.export_id AND x.canonical_sha256=h.canonical_sha256 AND b.target_binding_id!=NEW.target_binding_id) THEN RAISE(ABORT,'equivalent handoff target split') END;
END;
CREATE TRIGGER handoff_binding_no_update BEFORE UPDATE ON sheet_handoff_bindings BEGIN SELECT RAISE(ABORT,'sheet handoff binding is immutable'); END;
CREATE TRIGGER handoff_binding_no_delete BEFORE DELETE ON sheet_handoff_bindings BEGIN SELECT RAISE(ABORT,'sheet handoff binding cannot be deleted'); END;
CREATE TRIGGER bootstrap_no_delete BEFORE DELETE ON sheet_bootstraps BEGIN SELECT RAISE(ABORT,'sheet bootstrap cannot be deleted'); END;
CREATE TRIGGER bootstrap_update BEFORE UPDATE ON sheet_bootstraps BEGIN
 SELECT CASE WHEN NEW.target_binding_id!=OLD.target_binding_id OR NEW.marker_value!=OLD.marker_value OR NEW.controls_fingerprint!=OLD.controls_fingerprint THEN RAISE(ABORT,'bootstrap identity is immutable') END;
 SELECT CASE WHEN OLD.status IN ('ready','manual_required') THEN RAISE(ABORT,'terminal bootstrap is immutable') END;
 SELECT CASE WHEN NOT ((OLD.status IN ('uninitialized','retryable') AND NEW.status='configuring') OR (OLD.status='configuring' AND NEW.status IN ('ready','retryable','blocked','ambiguous')) OR (OLD.status='ambiguous' AND NEW.status IN ('ready','retryable','blocked','manual_required')) OR (OLD.status='blocked' AND NEW.status='retryable')) THEN RAISE(ABORT,'illegal bootstrap transition') END;
 SELECT CASE WHEN OLD.status='ambiguous' AND NEW.status='retryable' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version AND e.event_kind='trusted_rejection' WHERE o.target_binding_id=OLD.target_binding_id AND o.operation_kind='bootstrap' AND o.status='rejected_retryable' AND aware_epoch_us(NEW.retry_at)>aware_epoch_us(e.occurred_at)) THEN RAISE(ABORT,'retry deadline invalid') END;
 SELECT CASE WHEN OLD.status='blocked' AND NEW.status='retryable' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version AND e.event_kind='operator_corrected' AND e.safe_code=OLD.safe_error_code AND e.occurred_at=NEW.retry_at WHERE o.target_binding_id=OLD.target_binding_id AND o.operation_kind='bootstrap' AND o.finished_at IS NOT NULL AND (o.status='rejected_blocked' OR (o.status='blocked' AND o.outcome='schema_conflict' AND o.certainty='settled_not_applied')) AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations open WHERE open.target_binding_id=o.target_binding_id AND open.finished_at IS NULL)) THEN RAISE(ABORT,'operator correction invalid') END;
 SELECT CASE WHEN NOT (OLD.status='blocked' AND NEW.status='retryable') AND NOT EXISTS(
   SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.operation_id=o.id AND l.fence_version=o.last_fence_version AND l.status='active'
   JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version
   WHERE o.target_binding_id=OLD.target_binding_id AND o.operation_kind='bootstrap' AND (
    (OLD.status IN ('uninitialized','retryable') AND NEW.status='configuring' AND (OLD.status='uninitialized' OR aware_epoch_us(OLD.retry_at)<=aware_epoch_us(e.occurred_at)) AND l.lease_mode='mutate' AND o.status='acquired' AND e.event_kind='acquired')
    OR (OLD.status='configuring' AND NEW.status='ambiguous' AND l.lease_mode='mutate' AND o.status='possibly_sent' AND e.event_kind='dispatch_marked')
    OR (OLD.status='configuring' AND NEW.status='retryable' AND l.lease_mode='mutate' AND o.status='abandoned_pre_marker' AND e.event_kind='lease_expired_pre_marker')
    OR (OLD.status IN ('configuring','ambiguous') AND NEW.status IN ('ready','blocked','manual_required','retryable') AND e.event_kind IN ('finalized','trusted_rejection','operator_manual_required'))
   )
 ) THEN RAISE(ABORT,'bootstrap transition lacks active lease event') END;
END;
CREATE TRIGGER operation_no_delete BEFORE DELETE ON sheet_remote_operations BEGIN SELECT RAISE(ABORT,'operation cannot be deleted'); END;
CREATE TRIGGER operation_update BEFORE UPDATE ON sheet_remote_operations BEGIN
 SELECT CASE WHEN NEW.target_binding_id!=OLD.target_binding_id OR NEW.operation_kind!=OLD.operation_kind OR NEW.handoff_id IS NOT OLD.handoff_id OR NEW.ordinal!=OLD.ordinal OR NEW.acquired_at!=OLD.acquired_at THEN RAISE(ABORT,'operation identity is immutable') END;
 SELECT CASE WHEN OLD.finished_at IS NOT NULL THEN RAISE(ABORT,'terminal operation is immutable') END;
 SELECT CASE WHEN (NEW.last_fence_version=OLD.last_fence_version AND (NEW.current_acquired_event_id!=OLD.current_acquired_event_id OR NEW.current_lease_id!=OLD.current_lease_id)) OR (NEW.last_fence_version!=OLD.last_fence_version AND (NEW.current_acquired_event_id=OLD.current_acquired_event_id OR NEW.current_lease_id=OLD.current_lease_id)) THEN RAISE(ABORT,'fence authority pointers changed illegally') END;
 SELECT CASE WHEN OLD.dispatch_at IS NOT NULL AND (NEW.dispatch_at!=OLD.dispatch_at OR NEW.diagnostic_probe_at!=OLD.diagnostic_probe_at OR NEW.request_sha256!=OLD.request_sha256 OR NEW.preflight_event_id!=OLD.preflight_event_id OR NEW.preflight_fence_version!=OLD.preflight_fence_version OR NEW.preflight_at!=OLD.preflight_at OR NEW.validated_oracle_fingerprint!=OLD.validated_oracle_fingerprint OR NEW.validated_controls_fingerprint!=OLD.validated_controls_fingerprint OR NEW.credential_refreshed_at!=OLD.credential_refreshed_at OR NEW.credential_expires_at!=OLD.credential_expires_at OR NEW.credential_scope_ok!=OLD.credential_scope_ok) THEN RAISE(ABORT,'dispatch marker is immutable') END;
 SELECT CASE WHEN NEW.last_fence_version!=OLD.last_fence_version AND (NEW.last_fence_version!=OLD.last_fence_version+1 OR EXISTS(SELECT 1 FROM sheet_operation_leases l WHERE l.operation_id=OLD.id AND l.status='active')) THEN RAISE(ABORT,'illegal fence rotation') END;
 SELECT CASE WHEN NEW.status=OLD.status AND (NEW.certainty!=OLD.certainty OR NEW.dispatch_at IS NOT OLD.dispatch_at OR NEW.diagnostic_probe_at IS NOT OLD.diagnostic_probe_at OR NEW.request_sha256 IS NOT OLD.request_sha256 OR NEW.preflight_event_id IS NOT OLD.preflight_event_id OR NEW.preflight_fence_version IS NOT OLD.preflight_fence_version OR NEW.preflight_at IS NOT OLD.preflight_at OR NEW.validated_oracle_fingerprint IS NOT OLD.validated_oracle_fingerprint OR NEW.validated_controls_fingerprint IS NOT OLD.validated_controls_fingerprint OR NEW.credential_refreshed_at IS NOT OLD.credential_refreshed_at OR NEW.credential_expires_at IS NOT OLD.credential_expires_at OR NEW.credential_scope_ok IS NOT OLD.credential_scope_ok OR NEW.finished_at IS NOT OLD.finished_at OR NEW.outcome IS NOT OLD.outcome OR NEW.safe_error_code IS NOT OLD.safe_error_code OR NEW.settlement_id IS NOT OLD.settlement_id) THEN RAISE(ABORT,'operation state changed without transition') END;
 SELECT CASE WHEN NEW.status!=OLD.status AND NOT ((OLD.status='acquired' AND NEW.status='possibly_sent' AND NEW.finished_at IS NULL) OR (OLD.status='acquired' AND ((NEW.status='applied' AND NEW.outcome='reused') OR (NEW.status='blocked' AND NEW.outcome IN ('duplicate_metadata','conflicting_metadata')) OR (NEW.status='abandoned_pre_marker' AND NEW.outcome='abandoned_pre_marker')) AND NEW.finished_at IS NOT NULL) OR (OLD.status='possibly_sent' AND NEW.status IN ('applied','rejected_retryable','rejected_blocked','blocked','corrupt','manual_required') AND NEW.finished_at IS NOT NULL)) THEN RAISE(ABORT,'illegal operation transition') END;
 SELECT CASE WHEN NEW.finished_at IS NOT NULL AND NOT ((NEW.operation_kind='delivery' AND EXISTS(SELECT 1 FROM sheet_handoffs h WHERE h.id=NEW.handoff_id AND h.status=CASE OLD.status WHEN 'acquired' THEN 'delivering' ELSE 'ambiguous' END)) OR (NEW.operation_kind='bootstrap' AND EXISTS(SELECT 1 FROM sheet_bootstraps b WHERE b.target_binding_id=NEW.target_binding_id AND b.status=CASE OLD.status WHEN 'acquired' THEN 'configuring' ELSE 'ambiguous' END))) THEN RAISE(ABORT,'operation subject state mismatch') END;
 SELECT CASE WHEN NEW.status='possibly_sent' AND OLD.status!='possibly_sent' AND NOT EXISTS(SELECT 1 FROM sheet_operation_events d JOIN sheet_operation_leases l ON l.operation_id=d.operation_id AND l.fence_version=d.fence_version AND l.status='active' AND l.lease_mode='mutate' JOIN sheet_operation_events p ON p.id=NEW.preflight_event_id AND p.operation_id=d.operation_id AND p.fence_version=d.fence_version AND p.fence_version=NEW.preflight_fence_version AND p.event_kind='preflight_absent' AND p.occurred_at=NEW.preflight_at JOIN sheet_target_bindings t ON t.id=NEW.target_binding_id JOIN sheet_bootstraps b ON b.target_binding_id=t.id WHERE d.operation_id=NEW.id AND d.fence_version=NEW.last_fence_version AND d.event_kind='dispatch_marked' AND d.occurred_at=NEW.dispatch_at AND aware_epoch_us(l.acquired_at)<=aware_epoch_us(NEW.preflight_at) AND aware_epoch_us(NEW.preflight_at)<=aware_epoch_us(NEW.dispatch_at) AND aware_epoch_us(NEW.preflight_at)<aware_epoch_us(l.expires_at) AND aware_epoch_us(NEW.dispatch_at)<aware_epoch_us(l.expires_at) AND NEW.validated_oracle_fingerprint=t.oracle_fingerprint AND NEW.validated_controls_fingerprint=b.controls_fingerprint AND ((NEW.operation_kind='delivery' AND b.status='ready') OR (NEW.operation_kind='bootstrap' AND b.status='configuring')) AND NEW.credential_scope_ok=1 AND aware_epoch_us(NEW.credential_refreshed_at)<=aware_epoch_us(NEW.dispatch_at) AND aware_epoch_us(NEW.credential_expires_at)>=aware_epoch_us(NEW.dispatch_at)+255000000) THEN RAISE(ABORT,'dispatch attestation invalid') END;
 SELECT CASE WHEN NEW.finished_at IS NOT NULL AND OLD.finished_at IS NULL AND NOT EXISTS(SELECT 1 FROM sheet_operation_events e JOIN sheet_operation_leases l ON l.operation_id=e.operation_id AND l.fence_version=e.fence_version AND l.status='active' WHERE e.operation_id=NEW.id AND e.fence_version=NEW.last_fence_version AND e.occurred_at=NEW.finished_at AND e.event_kind IN ('finalized','trusted_rejection','operator_manual_required','lease_expired_pre_marker')) THEN RAISE(ABORT,'finalization lacks matching active lease event') END;
END;
CREATE TRIGGER lease_insert BEFORE INSERT ON sheet_operation_leases BEGIN
 SELECT CASE WHEN lease_owner_hash() IS NULL OR lease_owner_hash()!=NEW.owner_token_hash THEN RAISE(ABORT,'lease lacks owner authority') END;
 SELECT CASE WHEN NEW.status!='active' OR NEW.finished_at IS NOT NULL OR NEW.finish_reason IS NOT NULL THEN RAISE(ABORT,'lease starts active') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.finished_at IS NULL AND o.last_fence_version=NEW.fence_version AND ((NEW.lease_mode='mutate' AND NEW.fence_version=1 AND o.status='acquired' AND o.dispatch_at IS NULL) OR (NEW.lease_mode='probe' AND o.status='possibly_sent'))) THEN RAISE(ABORT,'lease fence or mode invalid') END;
END;
CREATE TRIGGER lease_update BEFORE UPDATE ON sheet_operation_leases BEGIN
 SELECT CASE WHEN OLD.status!='active' OR NEW.operation_id!=OLD.operation_id OR NEW.fence_version!=OLD.fence_version OR NEW.owner_token_hash!=OLD.owner_token_hash OR NEW.lease_mode!=OLD.lease_mode OR NEW.acquired_at!=OLD.acquired_at OR NEW.expires_at!=OLD.expires_at OR NEW.status NOT IN ('released','expired') OR NEW.finished_at IS NULL OR NEW.finish_reason IS NULL THEN RAISE(ABORT,'illegal lease update') END;
 SELECT CASE WHEN NEW.status='released' AND (lease_owner_hash() IS NULL OR lease_owner_hash()!=OLD.owner_token_hash) THEN RAISE(ABORT,'lease finish lacks owner authority') END;
 SELECT CASE WHEN NEW.status='expired' AND NOT (aware_epoch_us(NEW.finished_at)>=aware_epoch_us(NEW.expires_at)) THEN RAISE(ABORT,'lease not expired') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM sheet_operation_events e WHERE e.operation_id=NEW.operation_id AND e.fence_version=NEW.fence_version AND e.event_kind=NEW.finish_reason AND e.occurred_at=NEW.finished_at) THEN RAISE(ABORT,'lease finish lacks matching event') END;
 SELECT CASE WHEN NEW.status='expired' AND NOT ((NEW.finish_reason='lease_expired_pre_marker' AND EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.status='abandoned_pre_marker')) OR (NEW.finish_reason='probe_unavailable' AND EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.status='possibly_sent'))) THEN RAISE(ABORT,'expired lease state mismatch') END;
 SELECT CASE WHEN NEW.status='released' AND NOT ((NEW.finish_reason IN ('transport_ambiguous','probe_absent','probe_unavailable') AND EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.status='possibly_sent')) OR (NEW.finish_reason='trusted_rejection' AND EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.status IN ('rejected_retryable','rejected_blocked'))) OR (NEW.finish_reason IN ('finalized','operator_manual_required') AND EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.finished_at IS NOT NULL))) THEN RAISE(ABORT,'released lease state mismatch') END;
END;
CREATE TRIGGER lease_no_delete BEFORE DELETE ON sheet_operation_leases BEGIN SELECT RAISE(ABORT,'lease history retained'); END;
CREATE TRIGGER event_insert BEFORE INSERT ON sheet_operation_events BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND NEW.fence_version<=o.last_fence_version) THEN RAISE(ABORT,'event foreign fence') END;
 SELECT CASE WHEN NEW.event_kind='acquired' AND lease_owner_hash() IS NULL THEN RAISE(ABORT,'acquired event lacks owner authority') END;
 SELECT CASE WHEN NEW.event_kind='acquired' AND (NEW.safe_code IS NOT NULL OR NOT EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.last_fence_version=NEW.fence_version AND o.finished_at IS NULL) OR EXISTS(SELECT 1 FROM sheet_operation_events e WHERE e.operation_id=NEW.operation_id AND e.fence_version=NEW.fence_version AND e.event_kind='acquired')) THEN RAISE(ABORT,'invalid acquired event') END;
 SELECT CASE WHEN NEW.event_kind IN ('preflight_exact','preflight_absent','preflight_conflict') AND (EXISTS(SELECT 1 FROM sheet_operation_events e WHERE e.operation_id=NEW.operation_id AND e.fence_version=NEW.fence_version AND e.event_kind IN ('preflight_exact','preflight_absent','preflight_conflict')) OR NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.operation_id=o.id AND l.fence_version=o.last_fence_version AND l.status='active' AND l.lease_mode='mutate' WHERE o.id=NEW.operation_id AND o.last_fence_version=NEW.fence_version AND o.status='acquired' AND o.dispatch_at IS NULL AND aware_epoch_us(l.acquired_at)<=aware_epoch_us(NEW.occurred_at) AND aware_epoch_us(NEW.occurred_at)<aware_epoch_us(l.expires_at))) THEN RAISE(ABORT,'invalid immutable preflight decision') END;
 SELECT CASE WHEN NEW.event_kind NOT IN ('acquired','operator_corrected') AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.operation_id=o.id AND l.fence_version=NEW.fence_version AND l.status='active' WHERE o.id=NEW.operation_id AND o.last_fence_version=NEW.fence_version AND o.finished_at IS NULL AND (lease_owner_hash()=l.owner_token_hash OR (NEW.event_kind IN ('lease_expired_pre_marker','probe_unavailable') AND aware_epoch_us(l.expires_at)<=aware_epoch_us(NEW.occurred_at)))) THEN RAISE(ABORT,'event lacks current lease authority') END;
 SELECT CASE WHEN NEW.event_kind='operator_corrected' AND (NEW.safe_code NOT IN ('template_drift','metadata_conflict','not_found','invalid_request','unauthenticated','permission_denied','schema_conflict') OR NOT EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.last_fence_version=NEW.fence_version AND o.finished_at IS NOT NULL AND (o.status='rejected_blocked' OR (o.status='blocked' AND o.outcome='schema_conflict' AND o.certainty='settled_not_applied')) AND ((o.operation_kind='delivery' AND EXISTS(SELECT 1 FROM sheet_handoffs h WHERE h.id=o.handoff_id AND h.status='blocked' AND h.safe_error_code=NEW.safe_code)) OR (o.operation_kind='bootstrap' AND EXISTS(SELECT 1 FROM sheet_bootstraps b WHERE b.target_binding_id=o.target_binding_id AND b.status='blocked' AND b.safe_error_code=NEW.safe_code))) AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations open WHERE open.target_binding_id=o.target_binding_id AND open.finished_at IS NULL))) THEN RAISE(ABORT,'operator correction event invalid') END;
 SELECT CASE WHEN NEW.event_kind='dispatch_marked' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.operation_id=o.id AND l.fence_version=o.last_fence_version AND l.status='active' AND l.lease_mode='mutate' JOIN sheet_operation_events p ON p.operation_id=o.id AND p.fence_version=o.last_fence_version AND p.event_kind='preflight_absent' WHERE o.id=NEW.operation_id AND o.status='acquired' AND o.dispatch_at IS NULL AND aware_epoch_us(l.acquired_at)<=aware_epoch_us(p.occurred_at) AND aware_epoch_us(p.occurred_at)<=aware_epoch_us(NEW.occurred_at) AND aware_epoch_us(p.occurred_at)<aware_epoch_us(l.expires_at) AND aware_epoch_us(NEW.occurred_at)<aware_epoch_us(l.expires_at)) THEN RAISE(ABORT,'invalid dispatch event') END;
 SELECT CASE WHEN NEW.event_kind IN ('trusted_rejection','transport_ambiguous') AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.operation_id=o.id AND l.fence_version=o.last_fence_version AND l.status='active' AND l.lease_mode='mutate' WHERE o.id=NEW.operation_id AND o.status='possibly_sent') THEN RAISE(ABORT,'invalid post-marker event') END;
 SELECT CASE WHEN NEW.event_kind='trusted_rejection' AND NEW.safe_code IS NULL THEN RAISE(ABORT,'trusted rejection requires safe code') END;
 SELECT CASE WHEN NEW.event_kind='finalized' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND ((o.status='acquired' AND ((NEW.safe_code='reused' AND EXISTS(SELECT 1 FROM sheet_operation_events e WHERE e.operation_id=o.id AND e.fence_version=NEW.fence_version AND e.event_kind='preflight_exact')) OR (NEW.safe_code IN ('duplicate_metadata','conflicting_metadata') AND EXISTS(SELECT 1 FROM sheet_operation_events e WHERE e.operation_id=o.id AND e.fence_version=NEW.fence_version AND e.event_kind='preflight_conflict')))) OR (o.status='possibly_sent' AND ((NEW.safe_code='applied' AND EXISTS(SELECT 1 FROM sheet_operation_probes p WHERE p.operation_id=o.id AND p.fence_version=NEW.fence_version AND p.result='exact')) OR (NEW.safe_code='duplicate_metadata' AND EXISTS(SELECT 1 FROM sheet_operation_probes p WHERE p.operation_id=o.id AND p.fence_version=NEW.fence_version AND p.result='duplicate')) OR (NEW.safe_code IN ('conflicting_metadata','schema_conflict','local_corrupt') AND EXISTS(SELECT 1 FROM sheet_operation_probes p WHERE p.operation_id=o.id AND p.fence_version=NEW.fence_version AND p.result='conflict')))))) THEN RAISE(ABORT,'finalization evidence mismatch') END;
END;
CREATE TRIGGER event_no_update BEFORE UPDATE ON sheet_operation_events BEGIN SELECT RAISE(ABORT,'sheet event is immutable'); END;
CREATE TRIGGER event_no_delete BEFORE DELETE ON sheet_operation_events BEGIN SELECT RAISE(ABORT,'sheet event is immutable'); END;
CREATE TRIGGER probe_insert BEFORE INSERT ON sheet_operation_probes BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.operation_id=o.id AND l.fence_version=NEW.fence_version AND l.status='active' JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=NEW.fence_version AND e.event_kind='probe_'||NEW.result AND e.occurred_at=NEW.observed_at WHERE o.id=NEW.operation_id AND o.last_fence_version=NEW.fence_version AND o.status='possibly_sent' AND o.finished_at IS NULL AND lease_owner_hash()=l.owner_token_hash) THEN RAISE(ABORT,'probe lacks current owner event') END;
END;
CREATE TRIGGER probe_no_update BEFORE UPDATE ON sheet_operation_probes BEGIN SELECT RAISE(ABORT,'sheet probe is immutable'); END;
CREATE TRIGGER probe_no_delete BEFORE DELETE ON sheet_operation_probes BEGIN SELECT RAISE(ABORT,'sheet probe is immutable'); END;
CREATE TRIGGER settlement_insert BEFORE INSERT ON sheet_operation_settlements BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_leases l ON l.id=o.current_lease_id AND l.operation_id=o.id AND l.fence_version=o.last_fence_version WHERE o.id=NEW.operation_id AND o.settlement_id=NEW.id AND o.last_fence_version=NEW.fence_version AND o.status=NEW.operation_status AND o.outcome=NEW.outcome AND o.finished_at=NEW.settled_at AND l.status=NEW.lease_status AND l.finish_reason=NEW.lease_reason AND l.finished_at=NEW.settled_at AND ((o.operation_kind='delivery' AND EXISTS(SELECT 1 FROM sheet_handoffs h WHERE h.id=o.handoff_id AND h.status=NEW.subject_status)) OR (o.operation_kind='bootstrap' AND EXISTS(SELECT 1 FROM sheet_bootstraps b WHERE b.target_binding_id=o.target_binding_id AND b.status=NEW.subject_status)))) THEN RAISE(ABORT,'settlement partnership mismatch') END;
 SELECT CASE WHEN NOT (
  (NEW.outcome IN ('applied','reused') AND NEW.operation_status='applied' AND NEW.lease_status='released' AND NEW.lease_reason='finalized' AND ((EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.operation_kind='delivery') AND NEW.subject_status='delivered') OR (EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.operation_kind='bootstrap') AND NEW.subject_status='ready'))) OR
  (NEW.outcome='rejected_retryable' AND NEW.operation_status='rejected_retryable' AND NEW.subject_status='retryable' AND NEW.lease_status='released' AND NEW.lease_reason='trusted_rejection') OR
  (NEW.outcome='rejected_blocked' AND NEW.operation_status='rejected_blocked' AND NEW.subject_status='blocked' AND NEW.lease_status='released' AND NEW.lease_reason='trusted_rejection') OR
  (NEW.outcome='abandoned_pre_marker' AND NEW.operation_status='abandoned_pre_marker' AND NEW.subject_status='retryable' AND NEW.lease_status='expired' AND NEW.lease_reason='lease_expired_pre_marker') OR
  (NEW.outcome IN ('duplicate_metadata','conflicting_metadata','schema_conflict') AND NEW.operation_status='blocked' AND NEW.subject_status='blocked' AND NEW.lease_status='released' AND NEW.lease_reason='finalized') OR
  (NEW.outcome='local_corrupt' AND NEW.operation_status='corrupt' AND NEW.lease_status='released' AND NEW.lease_reason='finalized' AND ((EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.operation_kind='delivery') AND NEW.subject_status='corrupt') OR (EXISTS(SELECT 1 FROM sheet_remote_operations o WHERE o.id=NEW.operation_id AND o.operation_kind='bootstrap') AND NEW.subject_status='blocked'))) OR
  (NEW.outcome='operator_unresolved' AND NEW.operation_status='manual_required' AND NEW.subject_status='manual_required' AND NEW.lease_status='released' AND NEW.lease_reason='operator_manual_required')
 ) THEN RAISE(ABORT,'settlement outcome mismatch') END;
 SELECT CASE WHEN NEW.lease_reason='finalized' AND NOT EXISTS(SELECT 1 FROM sheet_operation_events e WHERE e.operation_id=NEW.operation_id AND e.fence_version=NEW.fence_version AND e.event_kind='finalized' AND e.safe_code=NEW.outcome AND e.occurred_at=NEW.settled_at) THEN RAISE(ABORT,'settlement evidence outcome mismatch') END;
 SELECT CASE WHEN NEW.lease_reason='trusted_rejection' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version AND e.event_kind='trusted_rejection' AND e.occurred_at=NEW.settled_at WHERE o.id=NEW.operation_id AND o.safe_error_code=e.safe_code AND ((NEW.outcome='rejected_retryable' AND e.safe_code IN ('aborted','rate_limited')) OR (NEW.outcome='rejected_blocked' AND e.safe_code IN ('template_drift','metadata_conflict','not_found','invalid_request','unauthenticated','permission_denied')))) THEN RAISE(ABORT,'trusted rejection taxonomy mismatch') END;
 SELECT CASE WHEN NEW.outcome='rejected_retryable' AND NOT EXISTS(SELECT 1 FROM sheet_remote_operations o JOIN sheet_operation_events e ON e.operation_id=o.id AND e.fence_version=o.last_fence_version AND e.event_kind='trusted_rejection' AND e.occurred_at=NEW.settled_at WHERE o.id=NEW.operation_id AND ((o.operation_kind='delivery' AND EXISTS(SELECT 1 FROM sheet_handoffs h WHERE h.id=o.handoff_id AND h.status='retryable' AND aware_epoch_us(e.occurred_at)<aware_epoch_us(h.retry_at))) OR (o.operation_kind='bootstrap' AND EXISTS(SELECT 1 FROM sheet_bootstraps b WHERE b.target_binding_id=o.target_binding_id AND b.status='retryable' AND aware_epoch_us(e.occurred_at)<aware_epoch_us(b.retry_at))))) THEN RAISE(ABORT,'settlement retry deadline invalid') END;
END;
CREATE TRIGGER settlement_no_update BEFORE UPDATE ON sheet_operation_settlements BEGIN SELECT RAISE(ABORT,'operation settlement is immutable'); END;
CREATE TRIGGER settlement_no_delete BEFORE DELETE ON sheet_operation_settlements BEGIN SELECT RAISE(ABORT,'operation settlement is immutable'); END;
PRAGMA foreign_key_check;
